#!/bin/bash

# Check if the user is root or can run sudo. If the User ID is not equal to 0 (root user)
# the prompt below will echo to the terminal to let the user know they need to run as sudo or root.

if [[ ! "$UID" -eq 0 ]]; then
	echo "You must run this script as sudo or root. Ex 'sudo ./install_packages'"
	exit 1
fi

# Define a list of packages to install
# the packages we want to install and we will use cat to read the contents
# of the packages.txt file and save it into the packages variable.
# Because the txt file is in the same directory we can just use the filename
# We also use wrap the command in another set of parenthases so it saves the contents as an array 

packages=($(cat "packages.txt"))

# Create a for loop to go over every package in the packages list array
# The @ symbol takes in all positional arguments as seperate strings (ex "kakoune" "tmux")

for pkg in ${packages[@]}; do

		# We will install the required packages using pacman -S (pacman is the arch linux package manager and -S will install the package from the repos or re-install them if they are already installed).
		# Once installed we echo the package has been installed

		pacman -S "$pkg"
		echo "$pkg has been installed"
done