#!/bin/bash

if [[ ! "$UID" -eq 0 ]]; then
	echo "You must run this script as sudo or root. Ex 'sudo ./symlinks' and don't forget to 'chmod +x symlinks' before that"
	exit 1
fi


# Symbolic link for the config directory and its files
ln -s /home/arch/2420-as2-starting-files/config/ /home/arch/.config/

# Symbolic link for the bin directory and its files
ln -s /home/arch/2420-as2-starting-files/bin/ /home/arch/bin/

# Symbolic link for the home directory
ln -s /home/arch/2420-as2-starting-files/home/bashrc /home/arch/.bashrc


echo "symbolic links created successfully!"
