#!/bin/bash

if [[ ! "$UID" -eq 0 ]]; then
	echo "You must run this script as sudo or root. Ex 'sudo ./symlinks' and don't forget to 'chmod +x symlinks' before that"
	exit 1
fi

# We can use the $USER variable which uses the current user's username executing the script.
# This way we can use the script on any user and it will create the symbolic links for that user.

# Symbolic link for the config directory and its files
ln -s /home/$USER/2420-as2-starting-files/config ~/.config

# Symbolic link for the bin directory and its files
ln -s /home/$USER/2420-as2-starting-files/bin ~/bin

# Symbolic link for the home directory
ln -s /home/$USER/2420-as2-starting-files/home/bashrc ~/.bashrc

echo "symbolic links created successfully!"
