#!/bin/bash

vara=""
varb=""

while getopts ":a:b:" opt; do
  case "${opt}" in
    a)
      vara=${OPTARG}
      ;;
    b)
      varb=${OPTARG}
      ;;
    :)
      echo "Error: -${OPTARG} requires an argument"
      exit 1
      ;;
    ?)
      exit 1
      ;;
  esac
done

if [[ -n $vara ]]; then
  echo "$vara"
fi

if [[ -n $varb ]]; then
  echo "$varb"
fi
